### ISSUE TITLE
Wireless data?

### ISSUE THREAD

**Issue by MartinSokolov15** [ramonmata/node-red-contrib-xbee#4]
Hi, can i obtain data from remote sensor wirelessly?

**Comment by ramonmata** [comment]
Hi @MartinSokolov15 In order to do that you may want send a command to some of your **XBee nodes** from the **Coordinator node** (the one connected to the Node-Red).

The XBee node may have a sensor attached or it may be used as a serial device with arduino and then you need to listen for the command and send back data.


Take a look at Digi documentation and samples
https://www.digi.com/resources/documentation/Digidocs/90001942-13/Default.htm#containers/cont_getting_started_with_xbee.htm

 
best of luck!
Ramon
